services:
  - type: web
    name: game-wiki-generator
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port --workers=2 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: RAWG_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: game-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    plan: free